version: '3'

services:
  neo4j:
    image: neo4j:4.0.4
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/connect
      NEO4J_dbms_memory_heap_max__size: 8G
      NEO4J_dbms_connector_https_advertised__address: 7473

    #      database explorer under http://localhost:7474/browser/

    mem_limit: 2048m
    mem_reservation: 2048M
    cpus: 2