version: '3'
services:
  db:
    image: postgres:13-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 25433:5432
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      
    # necessary for complex join queries, otherwise memory is limited to 64MB
    # https://stackoverflow.com/questions/56751565/pq-could-not-resize-shared-memory-segment-no-space-left-on-device
    shm_size: 1gb
    
volumes:
  pgdata: